HAPPY_OFFER_HOST = 
HAPPY_OFFER_USERNAME = 
HAPPY_OFFER_PASSWORD = 
HAPPY_OFFER_PASSWORD_SQLALCHEMY =
S3_BUCKET_ML = 
S3_BUCKET_ANALYTICS = 
LOG_GROUP_NAME = 

#prod_redshift
REDSHIFT_HOST = 
REDSHIFT_DATABASE = 
REDSHIFT_USERNAME = 
REDSHIFT_PASSWORD = 

#s3
AWS_ACCESS_KEY_ID = 
AWS_SECRET_ACCESS_KEY = 
